export {default as ProductList} from "../components/productList/productList"
export {default as ProductDetail} from "../components/productDetail/productDetail"
export {default as AddProduct} from "../components/addProductForm/addProductForm"
export {default as Panier} from "../components/panier/Panier"
export {default as Inscription} from "../components/inscription/Inscription"
export {default as Connexion} from "../components/connexion/Connexion"